server:
  port: 8099
  servlet:
    context-path: /
spring:
  application:
    name: yw-file
  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yw
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
mybatis:
  configuration:
    map-underscore-to-camel-case: true
