spring:
  application:
    name: eureka-server

server:
  port: 2001

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 192.168.1.9
  client:
    register-with-eureka: false
    fetch-registry: false
